# Generated by Django 3.2.7 on 2021-11-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(db_column='city', max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='state',
            name='acrm',
            field=models.CharField(db_column='acrm', max_length=3, verbose_name='acrm'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(db_column='state', max_length=50, verbose_name='state'),
        ),
    ]
