# Generated by Django 3.2.7 on 2021-10-05 15:06

import cpffield.cpffield
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(db_column='name_city', max_length=100)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_column='description')),
                ('date_of_creation', models.DateField()),
                ('amount_of_calories', models.DecimalField(db_column='amount_of_calories', decimal_places=1, max_digits=8)),
                ('weigh', models.DecimalField(db_column='weight', decimal_places=1, max_digits=8)),
            ],
            options={
                'db_table': 'diet_plan',
            },
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='type', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyHealthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obesity', models.BooleanField(db_column='obesity')),
                ('cardiovascular_disease', models.BooleanField(db_column='cardiovascular_disease')),
                ('hypertension', models.BooleanField(db_column='hypertension')),
                ('cancer', models.BooleanField(db_column='cancer')),
                ('diabetes', models.BooleanField(db_column='diabetes')),
                ('dyslipidemia', models.BooleanField(db_column='dyslipidemia')),
                ('others', models.TextField(db_column='others')),
            ],
            options={
                'db_table': 'family_health_history',
            },
        ),
        migrations.CreateModel(
            name='FoodConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_drink', models.BooleanField(db_column='soft_drink')),
                ('candy', models.BooleanField(db_column='candy')),
                ('deep_fried', models.BooleanField(db_column='deep_fried')),
                ('fast_food', models.BooleanField(db_column='fast_food')),
                ('processed_food', models.BooleanField(db_column='processed_food')),
                ('canned_food', models.BooleanField(db_column='canned')),
                ('fruits', models.BooleanField(db_column='fruits')),
                ('vegetables', models.BooleanField(db_column='vegetables')),
                ('others', models.TextField(db_column='description')),
            ],
            options={
                'db_table': 'food_consumption',
            },
        ),
        migrations.CreateModel(
            name='FoodDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_column='description')),
                ('date_of_consultation', models.DateField()),
                ('weight', models.DecimalField(db_column='weight', decimal_places=1, max_digits=4)),
            ],
            options={
                'db_table': 'food_diary',
            },
        ),
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_column='group', max_length=150)),
                ('weight', models.DecimalField(db_column='weight', decimal_places=1, max_digits=8)),
                ('calories', models.PositiveIntegerField(db_column='calories', default=0)),
            ],
            options={
                'db_table': 'food_group',
            },
        ),
        migrations.CreateModel(
            name='FoodIntolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intolerance_description', models.TextField(db_column='intolerance_description')),
            ],
            options={
                'db_table': 'food_intolerance',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', cpffield.cpffield.CPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('birthday', models.DateField()),
                ('email', models.CharField(db_column='email_patient', max_length=150)),
                ('street', models.CharField(db_column='street', max_length=50)),
                ('zip_code', models.CharField(db_column='zip_code', default='', max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.city')),
                ('family_health_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.familyhealthhistory')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='PatientHealthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obesity', models.BooleanField(db_column='obesity')),
                ('cardiovascular_disease', models.BooleanField(db_column='cardiovascular_disease')),
                ('hypertension', models.BooleanField(db_column='hypertension')),
                ('cancer', models.BooleanField(db_column='cancer')),
                ('diabetes', models.BooleanField(db_column='diabetes')),
                ('dyslipidemia', models.BooleanField(db_column='dyslipidemia')),
                ('others', models.TextField(db_column='others')),
            ],
            options={
                'db_table': 'patient_health_history',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_state', models.CharField(db_column='name_state', max_length=50)),
                ('acrm_state', models.CharField(db_column='acrm_state', max_length=3)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_column='phone_number', max_length=14)),
                ('description', models.TextField(db_column='description')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patient')),
            ],
            options={
                'db_table': 'phone',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_health_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patienthealthhistory'),
        ),
        migrations.AddField(
            model_name='patient',
            name='registered_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NutritionalConduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caloric_needs', models.DecimalField(db_column='caloric', decimal_places=2, max_digits=4)),
                ('additional_information', models.TextField(db_column='additional_information')),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.dietplan')),
                ('food_consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.foodconsumption')),
                ('food_intolerance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.foodintolerance')),
                ('food_preferences', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patient')),
            ],
            options={
                'db_table': 'nutricional_information',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_meal', models.CharField(db_column='type_meal', max_length=50)),
                ('time_meal', models.DateTimeField(db_column='time_meal')),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.dietplan')),
                ('food_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.fooddiary')),
                ('registered_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meal',
            },
        ),
        migrations.CreateModel(
            name='LabExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_exam', models.CharField(db_column='description', max_length=100)),
                ('date_of_exam', models.DateField()),
                ('upload', models.FileField(db_column='upload', upload_to='')),
                ('exam_information', models.TextField(db_column='name_exam ')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patient')),
                ('register_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_exam',
            },
        ),
        migrations.CreateModel(
            name='GastrointestinalTractSymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dysphagia', models.BooleanField(db_column='dysphagia')),
                ('pain', models.BooleanField(db_column='pain')),
                ('reflux', models.BooleanField(db_column='reflux')),
                ('heart_burn', models.BooleanField(db_column='heart_burn')),
                ('constipation', models.BooleanField(db_column='constipation')),
                ('nausea', models.BooleanField(db_column='nausea')),
                ('diarrhea', models.BooleanField(db_column='diarrhea')),
                ('others', models.TextField(db_column='description')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patient')),
                ('registered_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gastrointestinalt_tract_symptoms',
            },
        ),
        migrations.CreateModel(
            name='FoodPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_column='description')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patient')),
            ],
            options={
                'db_table': 'food_preferences',
            },
        ),
        migrations.AddField(
            model_name='foodintolerance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patient'),
        ),
        migrations.AddField(
            model_name='fooddiary',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patient'),
        ),
        migrations.AddField(
            model_name='fooddiary',
            name='registered_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodconsumption',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patient'),
        ),
        migrations.AddField(
            model_name='foodconsumption',
            name='registered_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(db_column='food_name', max_length=50)),
                ('weigh', models.DecimalField(db_column='weight', decimal_places=1, max_digits=8)),
                ('diet_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.dietplan')),
                ('food_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.foodgroup')),
            ],
            options={
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(db_column='frequency', max_length=255)),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.exercisetype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(db_column='hire_date')),
                ('cpf', cpffield.cpffield.CPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('birthday', models.DateField()),
                ('email', models.CharField(db_column='email_patient', max_length=150)),
                ('street', models.CharField(db_column='street', max_length=50)),
                ('zip_code', models.CharField(default='', max_length=9)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.city')),
                ('registered_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.AddField(
            model_name='dietplan',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patient'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='registered_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClinicEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nails', models.CharField(db_column='nails', max_length=100)),
                ('skin', models.CharField(db_column='skin', max_length=100)),
                ('bladder_habits', models.CharField(db_column='bladder_habits', max_length=100)),
                ('bowel_habits', models.CharField(db_column='bowel_habits', max_length=100)),
                ('additional_information', models.TextField(db_column='additional_information')),
                ('date_of_consultation', models.DateField()),
                ('updated', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patient')),
                ('registered_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinic_evaluation',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.state'),
        ),
        migrations.CreateModel(
            name='AntopometricEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(db_column='weight', decimal_places=2, max_digits=6)),
                ('height', models.CharField(db_column='height', max_length=4)),
                ('BMI', models.DecimalField(db_column='ibm', decimal_places=2, max_digits=4)),
                ('arm_circumference', models.DecimalField(db_column='arm_circumference', decimal_places=2, max_digits=4)),
                ('abdomen_circumference', models.DecimalField(db_column='abdomen_circumference', decimal_places=2, max_digits=4)),
                ('wrist_circumference', models.DecimalField(db_column='wrist_circumference', decimal_places=2, max_digits=4)),
                ('date_of_consultation', models.DateField()),
                ('updated', models.DateField()),
                ('additional_information', models.TextField(db_column='additional_information')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patient')),
                ('registeres_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'antopometric_evaluation',
            },
        ),
    ]
