# Generated by Django 3.2.7 on 2021-09-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_meal', models.CharField(db_column='type_meal', max_length=50)),
                ('time_meal', models.DateTimeField(auto_now_add=True, db_column='time_meal')),
            ],
            options={
                'db_table': 'Meal',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_state', models.CharField(db_column='name_state', max_length=50)),
                ('acrm_state', models.CharField(db_column='acrm_state', max_length=3)),
            ],
            options={
                'db_table': 'State',
            },
        ),
    ]
