# Generated by Django 3.2.7 on 2021-09-21 22:58

import cpffield.cpffield
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_meal_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name_city', models.CharField(db_column='name_city', max_length=50)),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='management.state')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(db_column='name_group', max_length=150)),
                ('gram_weight', models.DecimalField(decimal_places=1, help_text='gram_weight', max_digits=8)),
                ('calorie', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'food_group',
            },
        ),
        migrations.AlterModelTable(
            name='meal',
            table='meal',
        ),
        migrations.AlterModelTable(
            name='state',
            table='state',
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('register_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='management.user')),
                ('cpf', cpffield.cpffield.CPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('birthday', models.DateField()),
                ('email', models.CharField(db_column='email_patient', max_length=150)),
                ('street', models.CharField(max_length=50)),
                ('zip_code', models.CharField(default='', max_length=9)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.city')),
            ],
        ),
    ]
