# Generated by Django 3.2.7 on 2021-09-22 01:50

import cpffield.cpffield
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20210921_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('register_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='management.user')),
                ('type', models.CharField(db_column='type', max_length=50)),
                ('cpf', cpffield.cpffield.CPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('birthday', models.DateField()),
                ('email', models.CharField(db_column='email_patient', max_length=150)),
                ('street', models.CharField(max_length=50)),
                ('zip_code', models.CharField(default='', max_length=9)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.city')),
            ],
        ),
    ]
