# Generated by Django 3.2.7 on 2021-12-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_drink', models.BooleanField(db_column='soft_drink', verbose_name='soft_drink')),
                ('candy', models.BooleanField(db_column='candy', verbose_name='candy')),
                ('deep_fried', models.BooleanField(db_column='deep_fried', verbose_name='deep_fried')),
                ('fast_food', models.BooleanField(db_column='fast_food', verbose_name='fast_food')),
                ('processed_food', models.BooleanField(db_column='processed_food', verbose_name='processed_food')),
                ('canned_food', models.BooleanField(db_column='canned', verbose_name='canned')),
                ('fruits', models.BooleanField(db_column='fruits', verbose_name='fruits')),
                ('vegetables', models.BooleanField(db_column='vegetables', verbose_name='vegetables')),
                ('others', models.TextField(blank=True, db_column='description', verbose_name='description')),
            ],
            options={
                'verbose_name': 'Food Consuption',
                'verbose_name_plural': 'Food Consuptions',
                'db_table': 'food_consumption',
            },
        ),
        migrations.CreateModel(
            name='FoodPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, db_column='description', verbose_name='description')),
                ('food_consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_consumption.foodconsumption', verbose_name='food_consumption')),
            ],
            options={
                'verbose_name': 'Food Preference',
                'verbose_name_plural': 'Food Preferences',
                'db_table': 'food_preferences',
            },
        ),
        migrations.CreateModel(
            name='FoodIntolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intolerance_description', models.TextField(db_column='intolerance_description', verbose_name='intolerance_description')),
                ('food_consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_consumption.foodconsumption', verbose_name='food_consumption')),
            ],
            options={
                'verbose_name': 'Food Intolerance',
                'verbose_name_plural': 'Food Intolerances',
                'db_table': 'food_intolerance',
            },
        ),
    ]
