# Generated by Django 3.2.7 on 2021-11-06 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20211106_0131'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_consumption', '0003_foodconsumption_registered_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodconsumption',
            options={'verbose_name': 'Food Consuption', 'verbose_name_plural': 'Food Consuptions'},
        ),
        migrations.AlterModelOptions(
            name='foodintolerance',
            options={'verbose_name': 'Food Intolerance', 'verbose_name_plural': 'Food Intolerances'},
        ),
        migrations.AlterModelOptions(
            name='foodpreferences',
            options={'verbose_name': 'Food Preference', 'verbose_name_plural': 'Food Preferences'},
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='candy',
            field=models.BooleanField(db_column='candy', verbose_name='candy'),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='canned_food',
            field=models.BooleanField(db_column='canned', verbose_name='canned'),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='deep_fried',
            field=models.BooleanField(db_column='deep_fried', verbose_name='deep_fried'),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='fast_food',
            field=models.BooleanField(db_column='fast_food', verbose_name='fast_food'),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='fruits',
            field=models.BooleanField(db_column='fruits', verbose_name='fruits'),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='others',
            field=models.TextField(blank=True, db_column='description', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient', verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='processed_food',
            field=models.BooleanField(db_column='processed_food', verbose_name='processed_food'),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='registered_by'),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='soft_drink',
            field=models.BooleanField(db_column='soft_drink', verbose_name='soft_drink'),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='vegetables',
            field=models.BooleanField(db_column='vegetables', verbose_name='vegetables'),
        ),
        migrations.AlterField(
            model_name='foodintolerance',
            name='food_consumption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_consumption.foodconsumption', verbose_name='food_consumption'),
        ),
        migrations.AlterField(
            model_name='foodintolerance',
            name='intolerance_description',
            field=models.TextField(db_column='intolerance_description', verbose_name='intolerance_description'),
        ),
        migrations.AlterField(
            model_name='foodpreferences',
            name='description',
            field=models.TextField(blank=True, db_column='description', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='foodpreferences',
            name='food_consumption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_consumption.foodconsumption', verbose_name='food_consumption'),
        ),
    ]
