# Generated by Django 3.2.7 on 2021-11-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_consumption', '0003_foodconsumption_registered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodintolerance',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='foodpreferences',
            name='patient',
        ),
    ]
