# Generated by Django 3.2.7 on 2021-11-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_consumption', '0004_alter_foodconsumption_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodconsumption',
            name='others',
            field=models.TextField(blank=True, db_column='description'),
        ),
        migrations.AlterField(
            model_name='foodpreferences',
            name='description',
            field=models.TextField(blank=True, db_column='description'),
        ),
    ]
