# Generated by Django 3.2.7 on 2021-11-06 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Phone', 'verbose_name_plural': 'Phones'},
        ),
        migrations.RemoveField(
            model_name='phone',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='patient',
        ),
        migrations.AddField(
            model_name='phone',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='object_id',
            field=models.PositiveIntegerField(default=1, verbose_name='object_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.TextField(db_column='description', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(db_column='phone_number', max_length=14, verbose_name='phone number'),
        ),
    ]
