# Generated by Django 3.2.7 on 2021-11-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_auto_20211106_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.CharField(db_column='description', max_length=200, verbose_name='description'),
        ),
    ]
