# Generated by Django 3.2.7 on 2021-11-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_column='description', verbose_name='description')),
                ('date_of_consultation', models.DateField(verbose_name='date_of_consultation')),
            ],
            options={
                'verbose_name': 'Food Diary',
                'verbose_name_plural': 'Food Diaries',
                'db_table': 'food_diary',
            },
        ),
    ]
