# Generated by Django 3.2.7 on 2021-11-04 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_diary', '0003_fooddiary_registered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddiary',
            name='weight',
        ),
    ]
