# Generated by Django 3.2.7 on 2021-11-08 20:45

import cpffield.cpffield
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(db_column='hire_date', verbose_name='hire_date')),
                ('cpf', cpffield.cpffield.CPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('email', models.CharField(db_column='email_patient', max_length=150, verbose_name='email')),
                ('street', models.CharField(db_column='street', max_length=50, verbose_name='address')),
                ('zip_code', models.CharField(default='', max_length=9, verbose_name='zip code')),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='location.city', verbose_name='city')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee',
            },
        ),
    ]
