# Generated by Django 3.2.7 on 2021-11-06 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20211106_0131'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(db_column='email_patient', max_length=150, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(db_column='hire_date', verbose_name='hire_date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_by', to=settings.AUTH_USER_MODEL, verbose_name='registered_by'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.state', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='street',
            field=models.CharField(db_column='street', max_length=50, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zip_code',
            field=models.CharField(default='', max_length=9, verbose_name='zip code'),
        ),
    ]
