# Generated by Django 3.2.7 on 2021-11-06 16:08

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20211106_0131'),
        ('employee', '0003_auto_20211106_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='location.city', verbose_name='city'),
        ),
    ]
