# Generated by Django 3.2.7 on 2021-11-08 00:35

import cpffield.cpffield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=cpffield.cpffield.CPFField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
