XXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXX
        XXXXX X
            XXXXX XXX
            XXXXXXX XXXX
        X

        XXXXXX X
            XXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXX
        X

        XXXXXX XXX
        XXXXXX XX X
            XXXXXXXX XXXX
            XXXXXXXXXXXXXXX XXXX 
            XXXXXXXXXXX XXX XXXXX XXXXX
            XXXXXXXXXXX XXXXX
        X

        XXXXXX XXXXX XX X
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXX XXXXX XXXXX
            
        X

        XXXXXX XXXXX X XXXXX X
            XXXXXXXXXXX XXX XXXXX XXXXX
            XXXXXXXXXXX XXXXX
        X

        XXXXXX XXXXXX X
            XXXXXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXX XXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXX X X
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXXX
        X

    XXXXXXXX
XXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXXXX X  FFFFFFFFFFFFXXXXX
            XXXX XXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXX   XXXX 
                XXX XXXX  XXXX
                XXX XXXXXXXXXXXXXX  XXXX
                XXX XXXX XXXXXXXXX  XXXX
            XXXXXXXXXX
        XXXXXX

        XXXXXX XXXXXXXXXXXXXX
            XXXXXXX
            XXXX
                XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
                XXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
            XXXXX
            XXXXXXXX
            XXXXXXX
            BBB BBBB BB BBBBB
                BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
                XXXX
                    XXXXXXXXX
                    XXXX XXXXX
                    XXXX XXXXX
                    XXXXXXXXX
                    XXXX
                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                    XXXXX
                XXXXX
                BBBBBB
            BBBBBB
            XXXXXXXX
        XXXXXXXX
    XXXXXX
XXXXXX

XXXXXXX
XXXXXXX