# Generated by Django 3.2.7 on 2021-12-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_consultation', models.DateTimeField(verbose_name='date_of_consultation')),
                ('duration', models.DurationField(verbose_name='duration (minutes)')),
                ('reason', models.CharField(db_column='reason', max_length=200, verbose_name='reason')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'Appointment',
            },
        ),
    ]
