# Generated by Django 3.2.7 on 2021-10-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyHealthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obesity', models.BooleanField(db_column='obesity')),
                ('cardiovascular_disease', models.BooleanField(db_column='cardiovascular_disease')),
                ('hypertension', models.BooleanField(db_column='hypertension')),
                ('cancer', models.BooleanField(db_column='cancer')),
                ('diabetes', models.BooleanField(db_column='diabetes')),
                ('dyslipidemia', models.BooleanField(db_column='dyslipidemia')),
                ('others', models.TextField(db_column='others')),
            ],
            options={
                'db_table': 'family_health_history',
            },
        ),
        migrations.CreateModel(
            name='PatientHealthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obesity', models.BooleanField(db_column='obesity')),
                ('cardiovascular_disease', models.BooleanField(db_column='cardiovascular_disease')),
                ('hypertension', models.BooleanField(db_column='hypertension')),
                ('cancer', models.BooleanField(db_column='cancer')),
                ('diabetes', models.BooleanField(db_column='diabetes')),
                ('dyslipidemia', models.BooleanField(db_column='dyslipidemia')),
                ('others', models.TextField(db_column='others')),
            ],
            options={
                'db_table': 'patient_health_history',
            },
        ),
    ]
