# Generated by Django 3.2.7 on 2021-12-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyHealthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obesity', models.BooleanField(db_column='obesity', verbose_name='obesity')),
                ('cardiovascular_disease', models.BooleanField(db_column='cardiovascular_disease', verbose_name='cardiovascular_disease')),
                ('hypertension', models.BooleanField(db_column='hypertension', verbose_name='hypertension')),
                ('cancer', models.BooleanField(db_column='cancer', verbose_name='cancer')),
                ('diabetes', models.BooleanField(db_column='diabetes', verbose_name='diabetes')),
                ('dyslipidemia', models.BooleanField(db_column='dyslipidemia', verbose_name='dyslipidemia')),
                ('others', models.TextField(blank=True, db_column='others', verbose_name='others')),
            ],
            options={
                'verbose_name': 'Family Health History',
                'verbose_name_plural': 'Family Health Histories',
                'db_table': 'family_health_history',
            },
        ),
        migrations.CreateModel(
            name='PatientHealthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obesity', models.BooleanField(db_column='obesity', verbose_name='obesity')),
                ('cardiovascular_disease', models.BooleanField(db_column='cardiovascular_disease', verbose_name='cardiovascular_disease')),
                ('hypertension', models.BooleanField(db_column='hypertension', verbose_name='hypertension')),
                ('cancer', models.BooleanField(db_column='cancer', verbose_name='cancer')),
                ('diabetes', models.BooleanField(db_column='diabetes', verbose_name='diabetes')),
                ('dyslipidemia', models.BooleanField(db_column='dyslipidemia', verbose_name='dyslipidemia')),
                ('others', models.TextField(blank=True, db_column='others', verbose_name='other')),
            ],
            options={
                'verbose_name': 'Patient Health History',
                'verbose_name_plural': 'Patient Health Histories',
                'db_table': 'patient_health_history',
            },
        ),
    ]
