# Generated by Django 3.2.7 on 2021-12-03 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_history', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthealthhistory',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='registered_by'),
        ),
    ]
