# Generated by Django 3.2.7 on 2021-11-06 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20211106_0131'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_history', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyhealthhistory',
            options={'verbose_name': 'Family Health History', 'verbose_name_plural': 'Family Health Histories'},
        ),
        migrations.AlterModelOptions(
            name='patienthealthhistory',
            options={'verbose_name': 'Patient Health History', 'verbose_name_plural': 'Patient Health Histories'},
        ),
        migrations.AlterField(
            model_name='familyhealthhistory',
            name='cancer',
            field=models.BooleanField(db_column='cancer', verbose_name='cancer'),
        ),
        migrations.AlterField(
            model_name='familyhealthhistory',
            name='cardiovascular_disease',
            field=models.BooleanField(db_column='cardiovascular_disease', verbose_name='cardiovascular_disease'),
        ),
        migrations.AlterField(
            model_name='familyhealthhistory',
            name='diabetes',
            field=models.BooleanField(db_column='diabetes', verbose_name='diabetes'),
        ),
        migrations.AlterField(
            model_name='familyhealthhistory',
            name='dyslipidemia',
            field=models.BooleanField(db_column='dyslipidemia', verbose_name='dyslipidemia'),
        ),
        migrations.AlterField(
            model_name='familyhealthhistory',
            name='hypertension',
            field=models.BooleanField(db_column='hypertension', verbose_name='hypertension'),
        ),
        migrations.AlterField(
            model_name='familyhealthhistory',
            name='obesity',
            field=models.BooleanField(db_column='obesity', verbose_name='obesity'),
        ),
        migrations.AlterField(
            model_name='familyhealthhistory',
            name='others',
            field=models.TextField(blank=True, db_column='others', verbose_name='others'),
        ),
        migrations.AlterField(
            model_name='familyhealthhistory',
            name='patient_health_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_history.patienthealthhistory', verbose_name='patient_health_history'),
        ),
        migrations.AlterField(
            model_name='patienthealthhistory',
            name='cancer',
            field=models.BooleanField(db_column='cancer', verbose_name='cancer'),
        ),
        migrations.AlterField(
            model_name='patienthealthhistory',
            name='cardiovascular_disease',
            field=models.BooleanField(db_column='cardiovascular_disease', verbose_name='cardiovascular_disease'),
        ),
        migrations.AlterField(
            model_name='patienthealthhistory',
            name='diabetes',
            field=models.BooleanField(db_column='diabetes', verbose_name='diabetes'),
        ),
        migrations.AlterField(
            model_name='patienthealthhistory',
            name='dyslipidemia',
            field=models.BooleanField(db_column='dyslipidemia', verbose_name='dyslipidemia'),
        ),
        migrations.AlterField(
            model_name='patienthealthhistory',
            name='hypertension',
            field=models.BooleanField(db_column='hypertension', verbose_name='hypertension'),
        ),
        migrations.AlterField(
            model_name='patienthealthhistory',
            name='obesity',
            field=models.BooleanField(db_column='obesity', verbose_name='obesity'),
        ),
        migrations.AlterField(
            model_name='patienthealthhistory',
            name='others',
            field=models.TextField(blank=True, db_column='others', verbose_name='other'),
        ),
        migrations.AlterField(
            model_name='patienthealthhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient', verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='patienthealthhistory',
            name='registered_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='registered_by'),
        ),
    ]
