# Generated by Django 3.2.7 on 2021-11-01 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_history', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyhealthhistory',
            name='patient_health_history',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='health_history.patienthealthhistory'),
            preserve_default=False,
        ),
    ]
