# Generated by Django 3.2.7 on 2021-11-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_history', '0005_alter_familyhealthhistory_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthealthhistory',
            name='others',
            field=models.TextField(blank=True, db_column='others'),
        ),
    ]
