# Generated by Django 3.2.7 on 2021-11-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_history', '0006_alter_patienthealthhistory_others'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyhealthhistory',
            name='patient',
        ),
    ]
