# Generated by Django 3.2.7 on 2021-11-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_history', '0007_remove_familyhealthhistory_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyhealthhistory',
            name='registered_by',
        ),
    ]
