# Generated by Django 3.2.7 on 2021-11-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_column='description')),
                ('date_of_creation', models.DateField()),
            ],
            options={
                'db_table': 'diet_plan',
            },
        ),
    ]
