# Generated by Django 3.2.7 on 2021-10-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(db_column='weight', decimal_places=1, max_digits=8)),
            ],
            options={
                'db_table': 'diet_food',
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_column='description')),
                ('date_of_creation', models.DateField()),
                ('diet_food', models.ManyToManyField(related_name='diet_foods', through='diet_plan.DietFood', to='food_group.Food')),
            ],
            options={
                'db_table': 'diet_plan',
            },
        ),
    ]
