# Generated by Django 3.2.7 on 2021-10-26 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_group', '0001_initial'),
        ('diet_plan', '0002_dietplan_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='registered_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietfood',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_plan.dietplan'),
        ),
        migrations.AddField(
            model_name='dietfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_group.food'),
        ),
    ]
