# Generated by Django 3.2.7 on 2021-12-06 18:24

from django.db import migrations, models
import django.db.models.deletion
import nutribase.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_column='group', max_length=150, verbose_name='group')),
                ('calories', models.PositiveIntegerField(db_column='calories', default=0, validators=[nutribase.validators.validate_greater_than_zero], verbose_name='calories')),
            ],
            options={
                'verbose_name': 'Food Group',
                'verbose_name_plural': 'Food Groups',
                'db_table': 'food_group',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(db_column='food_name', max_length=50, verbose_name='food_name')),
                ('protein', models.DecimalField(db_column='protein', decimal_places=2, default=0.0, max_digits=8, verbose_name='protein')),
                ('lipids', models.DecimalField(db_column='lipids', decimal_places=2, default=0.0, max_digits=8, verbose_name='lipids')),
                ('cholesterol', models.DecimalField(db_column='cholesterol', decimal_places=2, default=0.0, max_digits=8, verbose_name='cholesterol')),
                ('carbohydrates', models.DecimalField(db_column='carbohydrates', decimal_places=2, default=0.0, max_digits=8, verbose_name='carbohydrates')),
                ('dietary_fiber', models.DecimalField(db_column='dietary_fiber', decimal_places=2, default=0.0, max_digits=8, verbose_name='dietary_fiber')),
                ('iron', models.DecimalField(db_column='iron', decimal_places=2, default=0.0, max_digits=8, verbose_name='iron')),
                ('vitamin_c', models.DecimalField(db_column='vitamin_C', decimal_places=2, default=0.0, max_digits=8, verbose_name='vitamin_C')),
                ('calcium', models.DecimalField(db_column='calcium', decimal_places=2, default=0.0, max_digits=8, verbose_name='calcium')),
                ('calories', models.DecimalField(db_column='calories', decimal_places=2, max_digits=8, verbose_name='calories')),
                ('weight', models.DecimalField(db_column='weight', decimal_places=2, max_digits=8, validators=[nutribase.validators.validate_greater_than_zero], verbose_name='weight')),
                ('food_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_group.foodgroup', verbose_name='food_group')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
                'db_table': 'food',
            },
        ),
    ]
