# Generated by Django 3.2.7 on 2021-11-06 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Food', 'verbose_name_plural': 'Foods'},
        ),
        migrations.AlterModelOptions(
            name='foodgroup',
            options={'verbose_name': 'Food Group', 'verbose_name_plural': 'Food Groups'},
        ),
        migrations.AlterField(
            model_name='food',
            name='calcium',
            field=models.DecimalField(db_column='calcium', decimal_places=2, max_digits=8, verbose_name='calcium'),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.DecimalField(db_column='calories', decimal_places=2, max_digits=8, verbose_name='calories'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.DecimalField(db_column='carbohydrates', decimal_places=2, max_digits=8, verbose_name='carbohydrates'),
        ),
        migrations.AlterField(
            model_name='food',
            name='cholesterol',
            field=models.DecimalField(db_column='cholesterol', decimal_places=2, max_digits=8, verbose_name='cholesterol'),
        ),
        migrations.AlterField(
            model_name='food',
            name='dietary_fiber',
            field=models.DecimalField(db_column='dietary_fiber', decimal_places=2, max_digits=8, verbose_name='dietary_fiber'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_group.foodgroup', verbose_name='food_group'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(db_column='food_name', max_length=50, verbose_name='food_name'),
        ),
        migrations.AlterField(
            model_name='food',
            name='iron',
            field=models.DecimalField(db_column='iron', decimal_places=2, max_digits=8, verbose_name='iron'),
        ),
        migrations.AlterField(
            model_name='food',
            name='lipids',
            field=models.DecimalField(db_column='lipids', decimal_places=2, max_digits=8, verbose_name='lipids'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(db_column='protein', decimal_places=2, max_digits=8, verbose_name='protein'),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitamin_c',
            field=models.DecimalField(db_column='vitamin_C', decimal_places=2, max_digits=8, verbose_name='vitamin_C'),
        ),
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.DecimalField(db_column='weight', decimal_places=2, max_digits=8, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='calories',
            field=models.PositiveIntegerField(db_column='calories', default=0, verbose_name='calories'),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='group',
            field=models.CharField(db_column='group', max_length=150, verbose_name='group'),
        ),
    ]
