# Generated by Django 3.2.7 on 2021-10-25 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='proteins',
            new_name='protein',
        ),
    ]
