# Generated by Django 3.2.7 on 2021-11-14 17:50

from django.db import migrations, models
import nutribase.validators


class Migration(migrations.Migration):

    dependencies = [
        ('food_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calcium',
            field=models.DecimalField(db_column='calcium', decimal_places=2, default=0.0, max_digits=8, verbose_name='calcium'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.DecimalField(db_column='carbohydrates', decimal_places=2, default=0.0, max_digits=8, verbose_name='carbohydrates'),
        ),
        migrations.AlterField(
            model_name='food',
            name='cholesterol',
            field=models.DecimalField(db_column='cholesterol', decimal_places=2, default=0.0, max_digits=8, verbose_name='cholesterol'),
        ),
        migrations.AlterField(
            model_name='food',
            name='dietary_fiber',
            field=models.DecimalField(db_column='dietary_fiber', decimal_places=2, default=0.0, max_digits=8, verbose_name='dietary_fiber'),
        ),
        migrations.AlterField(
            model_name='food',
            name='iron',
            field=models.DecimalField(db_column='iron', decimal_places=2, default=0.0, max_digits=8, verbose_name='iron'),
        ),
        migrations.AlterField(
            model_name='food',
            name='lipids',
            field=models.DecimalField(db_column='lipids', decimal_places=2, default=0.0, max_digits=8, verbose_name='lipids'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(db_column='protein', decimal_places=2, default=0.0, max_digits=8, verbose_name='protein'),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitamin_c',
            field=models.DecimalField(db_column='vitamin_C', decimal_places=2, default=0.0, max_digits=8, verbose_name='vitamin_C'),
        ),
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.DecimalField(db_column='weight', decimal_places=2, max_digits=8, validators=[nutribase.validators.validate_greater_than_zero], verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='calories',
            field=models.PositiveIntegerField(db_column='calories', default=0, validators=[nutribase.validators.validate_greater_than_zero], verbose_name='calories'),
        ),
    ]
