# Generated by Django 3.2.7 on 2021-10-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_group', '0002_auto_20211027_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cholesterol',
            field=models.DecimalField(db_column='cholesterol', decimal_places=2, max_digits=4),
        ),
    ]
