# Generated by Django 3.2.7 on 2021-10-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_group', '0003_alter_food_cholesterol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calcium',
            field=models.DecimalField(db_column='calcium', decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.DecimalField(db_column='calories', decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.DecimalField(db_column='carbohydrates', decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='cholesterol',
            field=models.DecimalField(db_column='cholesterol', decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='dietary_fiber',
            field=models.DecimalField(db_column='dietary_fiber', decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='iron',
            field=models.DecimalField(db_column='iron', decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='lipids',
            field=models.DecimalField(db_column='lipids', decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(db_column='protein', decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitamin_c',
            field=models.DecimalField(db_column='vitamin_C', decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.DecimalField(db_column='weight', decimal_places=2, max_digits=8),
        ),
    ]
