# Generated by Django 3.2.7 on 2021-11-06 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20211106_0131'),
        ('exercise', '0002_exercise_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='exercisetype',
            options={'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercisetype', verbose_name='exercise_type'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='frequency',
            field=models.CharField(db_column='frequency', max_length=255, verbose_name='frequency'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient', verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='name',
            field=models.CharField(db_column='type', max_length=255, verbose_name='name_exercise'),
        ),
        migrations.AlterModelTable(
            name='exercise',
            table='exercise',
        ),
    ]
