# Generated by Django 3.2.7 on 2021-11-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exercise', '0003_auto_20211106_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='object_id',
            field=models.PositiveIntegerField(default=1, verbose_name='object_id'),
            preserve_default=False,
        ),
    ]
