# Generated by Django 3.2.7 on 2021-11-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_auto_20211106_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(db_column='exercise_type', max_length=100, verbose_name='exercise_type'),
        ),
        migrations.DeleteModel(
            name='ExerciseType',
        ),
    ]
