# Generated by Django 3.2.7 on 2021-11-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20211106_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='object_id',
        ),
    ]
