# Generated by Django 3.2.7 on 2021-11-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_auto_20211106_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='high_intensity',
            field=models.BooleanField(db_column='high_intensity', default=1, verbose_name='high_intensity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='light_intensity',
            field=models.BooleanField(db_column='light_intensity', default=1, verbose_name='light_intensity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='moderate_intensity',
            field=models.BooleanField(db_column='moderate_intensity', default=1, verbose_name='moderate_intensity'),
            preserve_default=False,
        ),
    ]
