# Generated by Django 3.2.7 on 2021-11-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='time_meal',
            field=models.TimeField(db_column='time_meal', verbose_name='time_meal'),
        ),
    ]
