# Generated by Django 3.2.7 on 2021-11-06 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('food_group', '0002_auto_20211106_0131'),
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
        migrations.AlterModelOptions(
            name='mealfood',
            options={'verbose_name': 'Meal Foods', 'verbose_name_plural': 'Meal Foods'},
        ),
        migrations.AlterField(
            model_name='meal',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content_type'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='object_id'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time_meal',
            field=models.DateTimeField(db_column='time_meal', verbose_name='time_meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='type_meal',
            field=models.CharField(db_column='type_meal', max_length=50, verbose_name='type_meal'),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_group.food', verbose_name='food'),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.meal', verbose_name='meal'),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='weight',
            field=models.DecimalField(db_column='weight', decimal_places=1, max_digits=8, verbose_name='weight'),
        ),
    ]
