# Generated by Django 3.2.7 on 2021-11-14 17:50

from django.db import migrations, models
import nutribase.validators


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_alter_meal_time_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealfood',
            name='weight',
            field=models.DecimalField(db_column='weight', decimal_places=1, max_digits=8, validators=[nutribase.validators.validate_greater_than_zero], verbose_name='weight'),
        ),
    ]
