# Generated by Django 3.2.7 on 2021-11-02 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_meal_registered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='registered_by',
        ),
    ]
