# Generated by Django 3.2.7 on 2021-11-01 23:55

import cpffield.cpffield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cpf',
            field=cpffield.cpffield.CPFField(max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
