# Generated by Django 3.2.7 on 2021-11-06 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20211106_0131'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='location.city', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(db_column='email_patient', max_length=150, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='registered_by'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.state', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='street',
            field=models.CharField(db_column='street', max_length=50, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(db_column='zip_code', default='', max_length=15, verbose_name='zip code'),
        ),
    ]
