# Generated by Django 3.2.7 on 2021-11-08 22:46

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
