# Generated by Django 3.2.7 on 2021-11-08 00:35

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patient_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf'),
        ),
    ]
