# Generated by Django 3.2.7 on 2021-11-04 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet_plan', '0001_initial'),
        ('food_consumption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalConduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caloric_needs', models.DecimalField(db_column='caloric', decimal_places=3, max_digits=8)),
                ('additional_information', models.TextField(blank=True, db_column='additional_information')),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_plan.dietplan')),
                ('food_consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_consumption.foodconsumption')),
                ('food_intolerance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_consumption.foodintolerance')),
                ('food_preferences', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_consumption.foodpreferences')),
            ],
            options={
                'db_table': 'nutricional_conduct',
            },
        ),
    ]
