# Generated by Django 3.2.7 on 2021-11-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet_plan', '0001_initial'),
        ('food_consumption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalConduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_information', models.TextField(blank=True, db_column='additional_information', verbose_name='additional_information')),
                ('date_of_consultation', models.DateField(verbose_name='date_of_consultation')),
                ('exercise_type', models.CharField(choices=[('L', 'Light'), ('M', 'Moderate'), ('I', 'Intensive')], max_length=1, verbose_name='exercise')),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_plan.dietplan', verbose_name='diet_plan')),
                ('food_consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_consumption.foodconsumption', verbose_name='food_consumption')),
                ('food_intolerance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_consumption.foodintolerance', verbose_name='food_intolerance')),
                ('food_preferences', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_consumption.foodpreferences', verbose_name='food_preferences')),
            ],
            options={
                'verbose_name': 'Nutricional Conduct',
                'verbose_name_plural': 'Nutricional Conducts',
                'db_table': 'nutricional_conduct',
            },
        ),
    ]
