# Generated by Django 3.2.7 on 2021-11-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_conduct', '0002_nutritionalconduct_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionalconduct',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='nutritionalconduct',
            name='food_consumption',
        ),
        migrations.RemoveField(
            model_name='nutritionalconduct',
            name='food_intolerance',
        ),
        migrations.RemoveField(
            model_name='nutritionalconduct',
            name='food_preferences',
        ),
        migrations.AddField(
            model_name='nutritionalconduct',
            name='description_nutricional_conduct',
            field=models.TextField(blank=True, db_column='description_nutricional_conduct', verbose_name='description_nutricional_conduct'),
        ),
    ]
