# Generated by Django 3.2.7 on 2021-10-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_conduct', '0002_nutritionalconduct_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalconduct',
            name='caloric_needs',
            field=models.DecimalField(db_column='caloric', decimal_places=3, max_digits=8),
        ),
    ]
