# Generated by Django 3.2.7 on 2021-11-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_conduct', '0002_nutritionalconduct_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalconduct',
            name='additional_information',
            field=models.TextField(blank=True, db_column='additional_information'),
        ),
    ]
