# Generated by Django 3.2.7 on 2021-11-08 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antopometric_evaluation', '0004_remove_antopometricevaluation_bmi'),
        ('nutritional_conduct', '0003_auto_20211108_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionalconduct',
            name='avaliacao_antopometrica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='antopometric_evaluation.antopometricevaluation', verbose_name='avaliacao_antopometrica'),
            preserve_default=False,
        ),
    ]
