# Generated by Django 3.2.7 on 2021-10-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_conduct', '0003_alter_nutritionalconduct_caloric_needs'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nutritionalconduct',
            table='nutricional_conduct',
        ),
    ]
