# Generated by Django 3.2.7 on 2021-11-08 23:18

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('antopometric_evaluation', '0004_remove_antopometricevaluation_bmi'),
        ('nutritional_conduct', '0004_nutritionalconduct_avaliacao_antopometrica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionalconduct',
            name='avaliacao_antopometrica',
        ),
        migrations.AddField(
            model_name='nutritionalconduct',
            name='antopometric_evaluation',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='patient', chained_model_field='patient', default=1, on_delete=django.db.models.deletion.CASCADE, to='antopometric_evaluation.antopometricevaluation', verbose_name='antopomeetric_evaluation'),
            preserve_default=False,
        ),
    ]
