# Generated by Django 3.2.7 on 2021-11-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_conduct', '0005_auto_20211108_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalconduct',
            name='description_nutricional_conduct',
            field=models.TextField(blank=True, db_column='description_nutricional_conduct', verbose_name='Nutricional Conduct'),
        ),
    ]
