# Generated by Django 3.2.7 on 2021-11-10 02:07

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_cpf'),
        ('antopometric_evaluation', '0004_remove_antopometricevaluation_bmi'),
        ('nutritional_conduct', '0007_alter_nutritionalconduct_antopometric_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalconduct',
            name='antopometric_evaluation',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='patient', chained_model_field='patient', on_delete=django.db.models.deletion.CASCADE, to='antopometric_evaluation.antopometricevaluation', verbose_name='antopomeetric_evaluation'),
        ),
        migrations.AlterUniqueTogether(
            name='nutritionalconduct',
            unique_together={('patient', 'antopometric_evaluation')},
        ),
    ]
