# Generated by Django 3.2.7 on 2021-11-10 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_cpf'),
        ('antopometric_evaluation', '0004_remove_antopometricevaluation_bmi'),
        ('diet_plan', '0005_remove_dietplan_antopometric_evaluation'),
        ('nutritional_conduct', '0008_auto_20211110_0207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nutritionalconduct',
            unique_together={('patient', 'antopometric_evaluation', 'diet_plan')},
        ),
    ]
