# Generated by Django 3.2.7 on 2021-11-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_conduct', '0010_auto_20211110_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionalconduct',
            name='description_nutricional_conduct',
        ),
        migrations.AddField(
            model_name='nutritionalconduct',
            name='description_nutritional_conduct',
            field=models.TextField(blank=True, db_column='description_nutritional_conduct', verbose_name='Nutricional Conduct'),
        ),
        migrations.AlterModelTable(
            name='nutritionalconduct',
            table='nutritional_conduct',
        ),
    ]
